### ISSUE TITLE
将 Sphinx reST 源文件一并提交至 GitHub

### ISSUE THREAD

**Issue by liancheng** [huangzworks/pgsqlcn#1]
感谢发起本项目！一个问题是当前 repo 仅有 `gh-pages` 分支和编译后的 HTML 文件，不便于社区协助纠错和贡献。若能将 Sphinx reST 源文件一并提交，可以提高社区协作效率。这样做还可以利用 http://readthedocs.org 来自动编译和发布最新版本，从而完全避免提交编译产出的 HTML 文件，减小 repo 尺寸。

**Comment by huangzworks** [comment]
谢谢连城的意见，您提到的两个方面我都会考虑的。
